package com.sgj.microschoolsystem.model.bo;

import java.util.Date;

public class MarketItem {

    private String username;

    private String face_image;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market.id
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market.name
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market.description
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market.img
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market.poster_id
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    private String posterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market.connect
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    private String connect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market.school
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market.price
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market.create_time
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    private Date createTime;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getFace_image() {
        return face_image;
    }

    public void setFace_image(String face_image) {
        this.face_image = face_image;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getImg() {
        return img;
    }

    public void setImg(String img) {
        this.img = img;
    }

    public String getPosterId() {
        return posterId;
    }

    public void setPosterId(String posterId) {
        this.posterId = posterId;
    }

    public String getConnect() {
        return connect;
    }

    public void setConnect(String connect) {
        this.connect = connect;
    }

    public String getSchool() {
        return school;
    }

    public void setSchool(String school) {
        this.school = school;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}
