package com.sgj.microschoolsystem.mapper;

import com.sgj.microschoolsystem.model.ChatMsg;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ChatMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat May 04 18:59:52 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat May 04 18:59:52 CST 2019
     */
    int insert(ChatMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat May 04 18:59:52 CST 2019
     */
    ChatMsg selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat May 04 18:59:52 CST 2019
     */
    List<ChatMsg> selectAll();

    List<ChatMsg> getUnreadMsgList(@Param("acceptUserId") String acceptUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat May 04 18:59:52 CST 2019
     */
    int updateByPrimaryKey(ChatMsg record);
}