package com.sgj.microschoolsystem.mapper;

import com.sgj.microschoolsystem.model.Events;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface EventsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    int insert(Events record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    Events selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    List<Events> selectAll();

    List<Events> selectMySchool(@Param("school") String school);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    int updateByPrimaryKey(Events record);
}