package com.sgj.microschoolsystem.mapper;

import com.sgj.microschoolsystem.model.FriendsRequest;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface FriendsRequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends_request
     *
     * @mbg.generated Thu May 02 19:07:34 CST 2019
     */
    int deleteByPrimaryKey(String id);

    int deleteSendUserIdAndAcceptUserId(@Param("sendUserId") String sendUserId, @Param("acceptUserId") String acceptUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends_request
     *
     * @mbg.generated Thu May 02 19:07:34 CST 2019
     */
    int insert(FriendsRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends_request
     *
     * @mbg.generated Thu May 02 19:07:34 CST 2019
     */
    FriendsRequest selectByPrimaryKey(String id);

    FriendsRequest selectBySendUserIdAndAcceptUSerId(@Param("sendId") String sendId, @Param("acceptId") String acceptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends_request
     *
     * @mbg.generated Thu May 02 19:07:34 CST 2019
     */
    List<FriendsRequest> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends_request
     *
     * @mbg.generated Thu May 02 19:07:34 CST 2019
     */
    int updateByPrimaryKey(FriendsRequest record);
}