package com.sgj.microschoolsystem.mapper;

import com.sgj.microschoolsystem.model.ManagerTable;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ManagerTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_table
     *
     * @mbg.generated Tue May 28 18:44:11 CST 2019
     */
    int deleteByPrimaryKey(String managerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_table
     *
     * @mbg.generated Tue May 28 18:44:11 CST 2019
     */
    int insert(ManagerTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_table
     *
     * @mbg.generated Tue May 28 18:44:11 CST 2019
     */
    ManagerTable selectByPrimaryKey(String managerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_table
     *
     * @mbg.generated Tue May 28 18:44:11 CST 2019
     */
    List<ManagerTable> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_table
     *
     * @mbg.generated Tue May 28 18:44:11 CST 2019
     */
    int updateByPrimaryKey(ManagerTable record);
}