package com.sgj.microschoolsystem.mapper;

import com.sgj.microschoolsystem.model.Market;
import com.sgj.microschoolsystem.model.bo.MarketItem;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface MarketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    int insert(Market record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    Market selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    List<Market> selectAll();

    List<MarketItem> selectMySchool(@Param("school") String school);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    int updateByPrimaryKey(Market record);
}