package com.sgj.microschoolsystem.mapper;

import com.sgj.microschoolsystem.model.MyFriends;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface MyFriendsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Thu May 02 16:36:22 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Thu May 02 16:36:22 CST 2019
     */
    int insert(MyFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Thu May 02 16:36:22 CST 2019
     */
    MyFriends selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Thu May 02 16:36:22 CST 2019
     */
    List<MyFriends> selectAll();

    List<String> selectByMyUserId(@Param("myUserId") String myUserId);

    int updateByPrimaryKey(MyFriends record);
}