package com.sgj.microschoolsystem.mapper;

import com.sgj.microschoolsystem.model.Pageant;
import com.sgj.microschoolsystem.model.bo.PageantListAll;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface PageantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageant
     *
     * @mbg.generated Mon May 13 21:54:42 CST 2019
     */
    int deleteByPrimaryKey(String poster);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageant
     *
     * @mbg.generated Mon May 13 21:54:42 CST 2019
     */
    int insert(Pageant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageant
     *
     * @mbg.generated Mon May 13 21:54:42 CST 2019
     */
    Pageant selectByPrimaryKey(String poster);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageant
     *
     * @mbg.generated Mon May 13 21:54:42 CST 2019
     */
    List<PageantListAll> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageant
     *
     * @mbg.generated Mon May 13 21:54:42 CST 2019
     */
    int updateByPrimaryKey(Pageant record);
}