package com.sgj.microschoolsystem.mapper;

import com.sgj.microschoolsystem.model.Pyq;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface PyqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pyq
     *
     * @mbg.generated Thu May 09 18:37:31 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pyq
     *
     * @mbg.generated Thu May 09 18:37:31 CST 2019
     */
    int insert(Pyq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pyq
     *
     * @mbg.generated Thu May 09 18:37:31 CST 2019
     */
    Pyq selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pyq
     *
     * @mbg.generated Thu May 09 18:37:31 CST 2019
     */
    List<Pyq> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pyq
     *
     * @mbg.generated Thu May 09 18:37:31 CST 2019
     */
    int updateByPrimaryKey(Pyq record);
}