package com.sgj.microschoolsystem.mapper;

import com.sgj.microschoolsystem.model.Users;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Fri May 10 21:51:32 CST 2019
     */
    int deleteByPrimaryKey(@Param("id") String id, @Param("phone") String phone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Fri May 10 21:51:32 CST 2019
     */
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Fri May 10 21:51:32 CST 2019
     */
    Users selectByPrimaryKey(@Param("id") String id);


    Users selectByPhone(@Param("phone") String phone);

    Users selectByUsername(@Param("username") String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Fri May 10 21:51:32 CST 2019
     */
    List<Users> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Fri May 10 21:51:32 CST 2019
     */
    int updateByPrimaryKey(Users record);
}