package com.sgj.microschoolsystem.model;

import java.util.Date;

public class Events {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events.id
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events.name
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events.posterid
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    private String posterid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events.content
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events.url
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events.img
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events.create_time
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events.school_name
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    private String schoolName;

    private String dept;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events.id
     *
     * @return the value of events.id
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events.id
     *
     * @param id the value for events.id
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events.name
     *
     * @return the value of events.name
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events.name
     *
     * @param name the value for events.name
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events.posterid
     *
     * @return the value of events.posterid
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    public String getPosterid() {
        return posterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events.posterid
     *
     * @param posterid the value for events.posterid
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    public void setPosterid(String posterid) {
        this.posterid = posterid == null ? null : posterid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events.content
     *
     * @return the value of events.content
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events.content
     *
     * @param content the value for events.content
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events.url
     *
     * @return the value of events.url
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events.url
     *
     * @param url the value for events.url
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events.img
     *
     * @return the value of events.img
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events.img
     *
     * @param img the value for events.img
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events.create_time
     *
     * @return the value of events.create_time
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events.create_time
     *
     * @param createTime the value for events.create_time
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events.school_name
     *
     * @return the value of events.school_name
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events.school_name
     *
     * @param schoolName the value for events.school_name
     *
     * @mbg.generated Tue May 28 18:20:09 CST 2019
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }

    public String getDept() {
        return dept;
    }

    public void setDept(String dept) {
        this.dept = dept;
    }

    @Override
    public String toString() {
        return "Events{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", posterid='" + posterid + '\'' +
                ", content='" + content + '\'' +
                ", url='" + url + '\'' +
                ", img='" + img + '\'' +
                ", createTime=" + createTime +
                ", schoolName='" + schoolName + '\'' +
                '}';
    }
}