package com.sgj.microschoolsystem.model;

import java.util.Date;

public class Market {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market.id
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market.name
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market.description
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market.img
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market.poster_id
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    private String posterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market.connect
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    private String connect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market.school
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market.price
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market.create_time
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market.id
     *
     * @return the value of market.id
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market.id
     *
     * @param id the value for market.id
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market.name
     *
     * @return the value of market.name
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market.name
     *
     * @param name the value for market.name
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market.description
     *
     * @return the value of market.description
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market.description
     *
     * @param description the value for market.description
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market.img
     *
     * @return the value of market.img
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market.img
     *
     * @param img the value for market.img
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market.poster_id
     *
     * @return the value of market.poster_id
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    public String getPosterId() {
        return posterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market.poster_id
     *
     * @param posterId the value for market.poster_id
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    public void setPosterId(String posterId) {
        this.posterId = posterId == null ? null : posterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market.connect
     *
     * @return the value of market.connect
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    public String getConnect() {
        return connect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market.connect
     *
     * @param connect the value for market.connect
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    public void setConnect(String connect) {
        this.connect = connect == null ? null : connect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market.school
     *
     * @return the value of market.school
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market.school
     *
     * @param school the value for market.school
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market.price
     *
     * @return the value of market.price
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market.price
     *
     * @param price the value for market.price
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market.create_time
     *
     * @return the value of market.create_time
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market.create_time
     *
     * @param createTime the value for market.create_time
     *
     * @mbg.generated Sat May 11 15:44:07 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        return "Market{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", description='" + description + '\'' +
                ", img='" + img + '\'' +
                ", posterId='" + posterId + '\'' +
                ", connect='" + connect + '\'' +
                ", school='" + school + '\'' +
                ", price='" + price + '\'' +
                ", createTime=" + createTime +
                '}';
    }
}