package com.sgj.microschoolsystem.model;

public class Pageant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pageant.poster
     *
     * @mbg.generated Mon May 13 21:54:42 CST 2019
     */
    private String poster;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pageant.img
     *
     * @mbg.generated Mon May 13 21:54:42 CST 2019
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pageant.like_count
     *
     * @mbg.generated Mon May 13 21:54:42 CST 2019
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pageant.school_name
     *
     * @mbg.generated Mon May 13 21:54:42 CST 2019
     */
    private String schoolName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pageant.poster
     *
     * @return the value of pageant.poster
     *
     * @mbg.generated Mon May 13 21:54:42 CST 2019
     */
    public String getPoster() {
        return poster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pageant.poster
     *
     * @param poster the value for pageant.poster
     *
     * @mbg.generated Mon May 13 21:54:42 CST 2019
     */
    public void setPoster(String poster) {
        this.poster = poster == null ? null : poster.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pageant.img
     *
     * @return the value of pageant.img
     *
     * @mbg.generated Mon May 13 21:54:42 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pageant.img
     *
     * @param img the value for pageant.img
     *
     * @mbg.generated Mon May 13 21:54:42 CST 2019
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pageant.like_count
     *
     * @return the value of pageant.like_count
     *
     * @mbg.generated Mon May 13 21:54:42 CST 2019
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pageant.like_count
     *
     * @param likeCount the value for pageant.like_count
     *
     * @mbg.generated Mon May 13 21:54:42 CST 2019
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pageant.school_name
     *
     * @return the value of pageant.school_name
     *
     * @mbg.generated Mon May 13 21:54:42 CST 2019
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pageant.school_name
     *
     * @param schoolName the value for pageant.school_name
     *
     * @mbg.generated Mon May 13 21:54:42 CST 2019
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }
}