package com.sgj.microschoolsystem.model;

import java.util.Date;

public class PageantLike {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pageant_like.id
     *
     * @mbg.generated Mon Jun 03 05:05:30 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pageant_like.pageant_id
     *
     * @mbg.generated Mon Jun 03 05:05:30 CST 2019
     */
    private String pageantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pageant_like.liker_id
     *
     * @mbg.generated Mon Jun 03 05:05:30 CST 2019
     */
    private String likerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pageant_like.create_time
     *
     * @mbg.generated Mon Jun 03 05:05:30 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pageant_like.id
     *
     * @return the value of pageant_like.id
     *
     * @mbg.generated Mon Jun 03 05:05:30 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pageant_like.id
     *
     * @param id the value for pageant_like.id
     *
     * @mbg.generated Mon Jun 03 05:05:30 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pageant_like.pageant_id
     *
     * @return the value of pageant_like.pageant_id
     *
     * @mbg.generated Mon Jun 03 05:05:30 CST 2019
     */
    public String getPageantId() {
        return pageantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pageant_like.pageant_id
     *
     * @param pageantId the value for pageant_like.pageant_id
     *
     * @mbg.generated Mon Jun 03 05:05:30 CST 2019
     */
    public void setPageantId(String pageantId) {
        this.pageantId = pageantId == null ? null : pageantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pageant_like.liker_id
     *
     * @return the value of pageant_like.liker_id
     *
     * @mbg.generated Mon Jun 03 05:05:30 CST 2019
     */
    public String getLikerId() {
        return likerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pageant_like.liker_id
     *
     * @param likerId the value for pageant_like.liker_id
     *
     * @mbg.generated Mon Jun 03 05:05:30 CST 2019
     */
    public void setLikerId(String likerId) {
        this.likerId = likerId == null ? null : likerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pageant_like.create_time
     *
     * @return the value of pageant_like.create_time
     *
     * @mbg.generated Mon Jun 03 05:05:30 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pageant_like.create_time
     *
     * @param createTime the value for pageant_like.create_time
     *
     * @mbg.generated Mon Jun 03 05:05:30 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}