package com.sgj.microschoolsystem.model;

import java.util.Date;

public class Pyq {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pyq.id
     *
     * @mbg.generated Thu May 09 18:37:31 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pyq.poster_id
     *
     * @mbg.generated Thu May 09 18:37:31 CST 2019
     */
    private String posterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pyq.msg
     *
     * @mbg.generated Thu May 09 18:37:31 CST 2019
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pyq.picture_small
     *
     * @mbg.generated Thu May 09 18:37:31 CST 2019
     */
    private String pictureSmall;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pyq.picture
     *
     * @mbg.generated Thu May 09 18:37:31 CST 2019
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pyq.create_time
     *
     * @mbg.generated Thu May 09 18:37:31 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pyq.like_count
     *
     * @mbg.generated Thu May 09 18:37:31 CST 2019
     */
    private Integer likeCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pyq.id
     *
     * @return the value of pyq.id
     *
     * @mbg.generated Thu May 09 18:37:31 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pyq.id
     *
     * @param id the value for pyq.id
     *
     * @mbg.generated Thu May 09 18:37:31 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pyq.poster_id
     *
     * @return the value of pyq.poster_id
     *
     * @mbg.generated Thu May 09 18:37:31 CST 2019
     */
    public String getPosterId() {
        return posterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pyq.poster_id
     *
     * @param posterId the value for pyq.poster_id
     *
     * @mbg.generated Thu May 09 18:37:31 CST 2019
     */
    public void setPosterId(String posterId) {
        this.posterId = posterId == null ? null : posterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pyq.msg
     *
     * @return the value of pyq.msg
     *
     * @mbg.generated Thu May 09 18:37:31 CST 2019
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pyq.msg
     *
     * @param msg the value for pyq.msg
     *
     * @mbg.generated Thu May 09 18:37:31 CST 2019
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pyq.picture_small
     *
     * @return the value of pyq.picture_small
     *
     * @mbg.generated Thu May 09 18:37:31 CST 2019
     */
    public String getPictureSmall() {
        return pictureSmall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pyq.picture_small
     *
     * @param pictureSmall the value for pyq.picture_small
     *
     * @mbg.generated Thu May 09 18:37:31 CST 2019
     */
    public void setPictureSmall(String pictureSmall) {
        this.pictureSmall = pictureSmall == null ? null : pictureSmall.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pyq.picture
     *
     * @return the value of pyq.picture
     *
     * @mbg.generated Thu May 09 18:37:31 CST 2019
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pyq.picture
     *
     * @param picture the value for pyq.picture
     *
     * @mbg.generated Thu May 09 18:37:31 CST 2019
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pyq.create_time
     *
     * @return the value of pyq.create_time
     *
     * @mbg.generated Thu May 09 18:37:31 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pyq.create_time
     *
     * @param createTime the value for pyq.create_time
     *
     * @mbg.generated Thu May 09 18:37:31 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pyq.like_count
     *
     * @return the value of pyq.like_count
     *
     * @mbg.generated Thu May 09 18:37:31 CST 2019
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pyq.like_count
     *
     * @param likeCount the value for pyq.like_count
     *
     * @mbg.generated Thu May 09 18:37:31 CST 2019
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }
}